### ISSUE TITLE
npx hardhat test

### ISSUE THREAD

**Issue by hyokim07** [adrianhajdin/project_web3.0#23]
Thank you very much for your tutorial. I was doing all right until I execute the command "npx hardhat test" I am getting the following error: 
S D:\web3.0\smart_contract> npx hardhat test
× Help us improve Hardhat with anonymous crash reports & basic usage data? (Y/n) · true
Compiling 2 files with 0.8.4
Solidity compilation finished successfully

  Greeter
    1) Should return the new greeting once it's changed

  0 passing (434ms)
  1 failing

  1) Greeter
       Should return the new greeting once it's changed:
     Error: error:0308010C:digital envelope routines::unsupported
      at new Hash (node:internal/crypto/hash:67:19)
      at Object.createHash (node:crypto:130:10)
      at hash160 (node_modules\ethereum-cryptography\vendor\hdkey-without-crypto.js:249:21)
      at HDKey.set (node_modules\ethereum-cryptography\vendor\hdkey-without-crypto.js:50:24)
      at Function.HDKey.fromMasterSeed (node_modules\ethereum-cryptography\vendor\hdkey-without-crypto.js:194:20)
      at deriveKeyFromMnemonicAndPath (node_modules\hardhat\src\internal\util\keys-derivation.ts:21:27)
      at derivePrivateKeys (node_modules\hardhat\src\internal\core\providers\util.ts:29:52)
      at normalizeHardhatNetworkAccountsConfig (node_modules\hardhat\src\internal\core\providers\util.ts:56:10)
      at createProvider (node_modules\hardhat\src\internal\core\providers\construction.ts:78:59)
      at D:\web3.0\smart_contract\node_modules\hardhat\src\internal\core\runtime-environment.ts:80:28

An unexpected error occurred:

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at hash160 (D:\web3.0\smart_contract\node_modules\ethereum-cryptography\vendor\hdkey-without-crypto.js:249:21)
    at HDKey.set (D:\web3.0\smart_contract\node_modules\ethereum-cryptography\vendor\hdkey-without-crypto.js:50:24)
    at Function.HDKey.fromMasterSeed (D:\web3.0\smart_contract\node_modules\ethereum-cryptography\vendor\hdkey-without-crypto.js:194:20)
    at deriveKeyFromMnemonicAndPath (D:\web3.0\smart_contract\node_modules\hardhat\src\internal\util\keys-derivation.ts:21:27)
    at derivePrivateKeys (D:\web3.0\smart_contract\node_modules\hardhat\src\internal\core\providers\util.ts:29:52)
    at normalizeHardhatNetworkAccountsConfig (D:\web3.0\smart_contract\node_modules\hardhat\src\internal\core\providers\util.ts:56:10)
    at createProvider (D:\web3.0\smart_contract\node_modules\hardhat\src\internal\core\providers\construction.ts:78:59)
    at D:\web3.0\smart_contract\node_modules\hardhat\src\internal\core\runtime-environment.ts:80:28 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
PS D:\web3.0\smart_contract> 
What am I doing wrong?

**Comment by MarkJCG** [comment]
@hyokim07  I had the same problem. It has something to do with Node Version ^17.x

> 1. You could downgrade your node version to 16.x or lower.

> 2. Or you have to set **NODE_OPTIONS** to **openssl-legacy-provider**. For that you run the following in your terminal:

> > -  For **Windows**: SET NODE_OPTIONS=--openssl-legacy-provider
> > -  For **Linux/MacOS**: export NODE_OPTIONS=--openssl-legacy-provider

But as far as I know you have to set it every time you open a new terminal. So instead I changed the _**package.json**_ script for _test_.

Go into **smart_contract/package.json** and change the _test_ key as following:

> **_Old:_** `"test": "echo \"Error: no test specified\" && exit 1"`

> **_New:_** `"test": "SET NODE_OPTIONS=--openssl-legacy-provider && npx hardhat test"`

Now you can run instead of _npx hardtest test_: `npm test` (But you need to be in the directory of smart_contract.)
