### ISSUE TITLE
when removing dummy data , current transactions are not showing only blank field is showing

### ISSUE THREAD

**Issue by namanthaker** [adrianhajdin/project_web3.0#28]

**Comment by namanthaker** [comment]
showing some problem of transactions variable in Transactions.jsx    please help me

**Comment by BenjaminVermeulen** [comment]
Same for me

**Comment by IMPranshu** [comment]
Same for me. When I am checking the console I am getting a weird error. I have asked for it at this [link](https://ethereum.stackexchange.com/questions/123884/strange-error-showing-up-in-console-regarding-gas-fees)

**Comment by Thebks** [comment]
What is the exact error? 
if the error is "addressFrom is undefined" then you might have to change the `addressFrom: transaction.sender` to `addressFrom:transaction.from` because in your solidity contract in the event transfer you might have written `address from` so you have to say `addressFrom: transaction.from` and same goes for other fields too..

Hope it helps

**Comment by shishir-repos** [comment]
> What is the exact error? if the error is "addressFrom is undefined" then you might have to change the `addressFrom: transaction.sender` to `addressFrom:transaction.from` because in your solidity contract in the event transfer you might have written `address from` so you have to say `addressFrom: transaction.from` and same goes for other fields too..
> 
> Hope it helps

TypeError: Cannot read properties of undefined (reading 'toNumber')
    at TransactionContext.jsx:45:55
    at Array.map (<anonymous>)
    at getAllTransactions (TransactionContext.jsx:42:64)


PLEASE HELP!!!!!
