### ISSUE TITLE
TransactionContext.jsx problem [2:57:00]

### ISSUE THREAD

**Issue by gunnvong** [adrianhajdin/project_web3.0#56]
TypeError: transactionContract.getAllTransactions is not a function
    at getAllTransactions (TransactionContext.jsx:35:69)
    at checkIfWalletIsConnected (TransactionContext.jsx:52:17)

the error shows this but I tried checking with the master's code and copying all the codes in the file, yet, the problem still persist.

thank you in advance.

**Comment by syahoho** [comment]
hye i have the same problem

**Comment by Haris320** [comment]
> @hareesh-r hey did you get the answer for your problem actually i'm also facing the same issue

I had the same issue. I found out that I spelled it as addToBlockChain rather that addToBlockchain. Make sure the spelling matches your Transactions.json

**Comment by gunnvong** [comment]
I fixed it by redo the project all over again. However, not sure what I did wrong in my first try, but, I do believe that the functions and classes in the  “transactioncontext.jsx” in the first try must be in the wrong order or placed in the wrong place, thus, the function wasn’t working. Hope it helps.

**Comment by Raunak34** [comment]
having the same problem. if anyone got the solution please share.
