### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'toNumber')     at TransactionContext.jsx:45:55   

### ISSUE THREAD

**Issue by shishir-repos** [adrianhajdin/project_web3.0#65]
TypeError: Cannot read properties of undefined (reading 'toNumber')
    at TransactionContext.jsx:45:55
    at Array.map (<anonymous>)
    at getAllTransactions (TransactionContext.jsx:42:64)

PLEASE HELP!!!!

**Comment by Vathender** [comment]
Any luck?
